PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX loan: <http://www.semanticweb.org/ontology/loan_approval#>

DELETE { ?s ?p ?o }
WHERE {
  ?s a ?type .
  ?type rdfs:subClassOf* loan:Applicant .
  ?s ?p ?o .
  FILTER(?s != loan:SalariedEmployee && ?s != loan:SelfEmployed && ?s != loan:Retiree && ?s != loan:Student)
};

DELETE { ?loan ?p ?o }
WHERE {
  ?loan a ?type .
  ?type rdfs:subClassOf* loan:Loan .
  ?loan ?p ?o .
  FILTER(?loan != loan:Loan && ?loan != loan:PersonalLoan && ?loan != loan:HousingLoan && ?loan != loan:EducationLoan)
};
